env:
  global:
    TERM=dumb
group: trusty_lts
language: java
jdk:
- openjdk8
- oraclejdk8
install: true
before_install:
- source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
- stop_any 27017
script:
- export ROOT=$PWD
- >
  for path in \
    reactive-secured-sse \
    reactive-kotlin-see \
    spring-kotlin-example \
  ; do
    cd "$ROOT/$path"
    bash gradlew clean build
  done;
# 01 e2e
- cd $ROOT/spring-kotlin-example
- bash gradlew clean build
- sudo mkdir -p /var/app
- sudo mv -f ./app/build/libs/*.jar /var/app/01.jar
- sudo ln -s /var/app/01.jar /etc/init.d/01
- sudo service 01 start
- wait_for 8080
- sudo service 01 stop
- stop_any 8080
